// This file is generated

I_death_place_0 = [
"",
"",
"St. Luke's Memorial Hospital, Spokane, Spokane, Washington, USA",
"Sigourney, Keokuk, Iowa, USA",
"Josephine General Hospital, Grants Pass, Josephine, Oregon, USA",
"Portland, Multnomah, Oregon, USA",
"Grants Pass, Josephine, Oregon, USA",
"",
"Iowa, Johnson, Iowa, USA",
"",
"",
"",
"",
"Richmond, Contra Costa, California, USA",
"Maloy, Ringgold, Iowa, USA",
"Greene, Pennsylvania, USA",
"",
"Bedford, Taylor, Iowa, USA",
"Deschutes, Oregon, USA",
"",
"",
"Benton, Ringgold, Iowa, USA",
"",
"Greene, Pennsylvania, USA",
"",
"Yolo, Yolo, California, USA",
"Eureka, Humboldt, California, USA",
"Antelope, Nebraska, USA",
"",
"",
"",
"",
"",
"Woodburn, Marion, Oregon, USA",
"Roseburg, Douglas, Oregon, USA",
"Roseburg, Douglas, Oregon, USA",
"Whitman, Washington, USA",
"",
"Loma Linda, San Bernardino, California, USA",
"Loma Linda, San Bernardino, California, USA",
"",
"Mount Ayr, Ringgold, Iowa, USA",
"Center, Greene, Pennsylvania, USA",
"",
"Deschutes, Oregon, USA",
"",
"",
"Greene, Indiana, USA",
"",
"",
"",
"",
"",
"Watsonville Road, Soquel, Santa Cruz, California, USA",
"",
"",
"Sandpoint, Bonner, Idaho, USA",
"Omaha, Douglas, Nebraska, USA",
"Tillamook, Tillamook, Oregon, USA",
"",
"",
"",
"",
"",
"",
"",
"",
"Colfax, Whitman, Washington, USA",
"Douglas, Oregon, USA",
"Faribault, Rice, Minnesota, USA",
"",
"Center, Greene, Pennsylvania, USA",
"St. Charles Medical Center, Bend, Deschutes, Oregon, USA",
"Wisconsin, USA",
"",
"Los Angeles, Los Angeles, California, USA",
"Redmond, Deschutes, Oregon, USA",
"Cannon City, Rice, Minnesota, USA",
"Banning, Riverside, California, USA",
"",
"",
"",
"",
"",
"Hillsboro, Washington, Oregon, USA",
"Tillamook, Tillamook, Oregon, USA",
"Antelope, Nebraska, USA",
"Creighton, Knox, Nebraska, USA",
"Waubonsie, Ringgold, Iowa, USA",
"",
"",
"Mount Ayr, Ringgold, Iowa, USA",
"",
"Greene, Pennsylvania, USA",
"Maloy, Ringgold, Iowa, USA",
""
]
Dwr.ScriptLoaded('dwr_db_I_death_place_0.js');
