// This file is generated

I_note_0 = [
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nMarriage to Martha Beasley was second according to marriage record\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nContradicting information:\n</p>\n<p>\n1. Appearance: My Heritage Trees webpage states \"Blond and Blue eyes, seems to have acted as the oldest brother for the Dunlap children- keeping an eye on them and keeping in touch through the years.\"<br />\nHowever draft registration card states \"Grey\" eyes and \"Dark\" hair<br />\n2. Birth Date: Funeral announcement reports birth as \"Jan 25 1870\". Draft card states Jan 25 1873. Headstone states \"1870\".<br />\n3. Name: John Henry Beal (funeral announcement). Henry J (Headstone).\n</p>\n</div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n\"Funeral announcement of John Henry Beal, he often went by Henry John Beal, he took off the s off Beals.\"\n</p>\n</div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nMay have lived with grandfather John Ashcraft according to 1880 census (he would have been 6 yrs old)\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n6.0' 165lbs, brown eyes, brown hair, dark complexien - Per draft registration\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nHe was one of the pioneer settlers of Ringgold and Taylor counties.\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nJacob Cowell is listed on the 1860, 1870 and 1880 Dunkard, Greene, PA census as married to an Elizabeth and has children: Irene, Salantha, May, Anna, Daniel, David and Catherine. Could he have re-married?<br />\nI haven't added these records as I cannot at this point verify they relate to the same person.\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n<span style=\"font-size:12px;\">Obituary</span><br />\nFrom FindaGrave (https://www.findagrave.com/memorial/66835058/helen-harriet-chaney)\n</p>\n<p>\nMrs. Chaney died May 11, 2001, in Roseburg, OR. She was born September 15, 1914 in Hughson, CA and moved with her parents to Sutherlin, OR in 1923.\n</p>\n<p>\nShe was a member of Eastern Star in Oakland, OR and enjoyed traveling, gardening, music and various hobbies.\n</p>\n<p>\nSurvivors include her husband, Howard Chaney; one daughter, Arlene (Cowell) Blackwell and husband Don of Bend, OR,; one son, Delvin Squier and wife Janabel of Redmond, OR.; grandchildren, Dean Cowell and wife Sandi of Bend, OR, Dennis Cowell of Bend, OR, Jerry Blackwell and wife Chris of Chandler, AZ, Darren Squier and wife Angela of Redmond, OR, Steve Squier and wife Tina of Highlands Ranch, CO, Toby Squier and wife Sabrina of Prineville, OR,;step daughter Pamela Wilds and husband Edward of Umpqua, OR.; step grandchildren Nathan and Erin Wilds of Umpqua, OR. Mrs. Chaney is also survived by 12 great-grandchildren and two brothers, Bud Holm and wife Vera of Sutherlin, OR and Norman Holm and wife Marge of Vancouver, WA.\n</p>\n<p>\nMrs. Chaney was preceded in death by her parents, Elijah and Sarah Holm, one brother, Ivan Holm, and two husbands, Floyd Squier and Richard Kemp.\n</p>\n<p>\nA memorial service will be held at the First Methodist Church, 181 E. Second Street in Sutherlin, OR on Saturday, May 19, 2001 at 3 p.m. Private inurnment will be held in the Valley View Cemetery in Sutherlin at a later date.\n</p>\n<p>\n(Obit published in the Roseburg, OR \"The News-Review\")\n</p>\n<p>\n&nbsp;\n</p>\n<p>\nNotes: 1900 U.S. Census for Cornwall, Troy Prec., Troy town, Latah Co., Idaho:<br />\nEdward Holm Head M 56 Norway<br />\nMary Holm Wife F 54 Norway<br />\nJohnnie Holm Son M 20 Norway<br />\nElijah Holm Son M 17 Minn<br />\nMarcus Holm Son M 14 Wisc<br />\nMary Holm Dau F 12 Idaho\n</p>\n<p>\nMary had 5 children, all living.\n</p>\n<p>\n1910 U.S. Census for Yount Twp, Napa Co., CA:<br />\nElijah Holm Head M 26 Minnesota<br />\nSarah Holm Wife F 19 Washington<br />\nIvan Holm Son M 10 mos Idaho\n</p>\n<p>\nElijah Holm's parents &amp; brother Mark &amp; his wife reside next door to him. Sarah has had 1 child, living. Father Edward is a farmer; sons Mark &amp; Elijah are farm laborers.\n</p>\n<p>\nOn Sept. 12, 1918, the Elijah Holm family resided in Soquel, Santa Cruz Co., CA, farming.\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nThere is a similarly named person who was born/died in the same time frame and area. Her name was Katherine Elizabeth Holstein Ochs, born 9/19/1857, died 3/23/1944. Not the same person.\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nAccording to obituary: She was a kind and loving mother, a good wife and neighbor. Obituary was signed off \"...our darling mother\" by her living children Robert, James, Howard, Mary, Ada and Elva.\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nDescription according to WWII draft registration card.: Height 5'6\", eye color blue, hair color brown/bald, weight 137, complexion light brown. Small finger on right hand cut off.\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nThere were 2 Johann Henrich's who were born to Johann Hartmann Scheuermann and Elisabeth German. This Johann Henrich was the older of the two (he was 14 in 1766 whereas his younger brother was 8). There were 2 baptism dates listed, 01/03/1753 or 01/20/1755. I am assuming the older date was for this Johann Henrich.<br />\nSource: Volga German Institute page \"Scheuermann (Yagodnaya Polyana)\"\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nThere were rumors in the 1880s that Indians were going to storm Colfax so farmers went in with guns and the excited abated. Mrs. Schierman was once alone and encountered some Indians who seemed threatening. She saw a man riding in the distance on a white horse and said, \u201cMein Mann, Mein Mann,\u201d like he was her husband, so they rode off. Every spring and summer Indians went north through Endicott to the mountains to hunt. Conrad used to say that sometimes it would take a half-day for them all to pass. A group armed with bows and arrows came into Charley Laird\u201fs place one time and told them to cook a meal, but the family sneaked up to Conrad\u201fs and they got their guns. The Indians left but took plates and things down to the river. Another time Mrs. Aschenbrenner cooked biscuits for them. They sometimes camped down by the Lairds and Weitzes on the northwest side of the river.<br />\n(Source: The Berry Meadow Archives page 169 from Mr. Dave Schierman, oral history, Walla Walla, Washington, July 9, 1972 (with Richard Scheuerman and Evelyn Reich).)\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nAfter retiring, Don and Arlene became full-time RV\u2019ers, traveling around the country, while enjoying boating, snowmobiling and other outdoor activities.\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nBlue eyes, brown hair (according to WWI Draft Registration Card)\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nMrs Cowell was always ready and willing to help in sickness and trouble. She was baptized in the Methodist church when a young woman and remained in that faith until death.<br />\nGrandma Cowell was bedfast almost 5 years and was a patient sufferer all that time. She will be missed by her family, relatives and friends.\n</p>\n</div>\n</div>",
""
]
Dwr.ScriptLoaded('dwr_db_I_note_0.js');
