// This file is generated

F_marr_place_0 = [
"",
"",
"Sigourney, Keokuk, Iowa, USA",
"",
"Johnson, Iowa, USA",
"Spokane, Spokane, Washington, USA",
"Hendricks, Indiana, USA",
"",
"Douglas, Oregon, USA",
"Davistown, Fayette, Pennsylvania, USA",
"",
"",
"Mount Ayr, Ringgold, Iowa, USA",
"Indianola, Warren, Iowa, USA",
"",
"",
"Reach, Ontario, Canada",
"",
"Great Falls, Cascade, Montana, USA",
"",
"Ober-Lais, Nidda, Hesse, Germany",
"",
"",
"",
"Rush, Indiana, USA",
"Northumberland, Pennsylvania, USA",
"",
"Endicott, Whitman, Washington, USA",
"",
"",
"Greene, Indiana, USA",
"Greene, Indiana, USA",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Rice, Minnesota, USA",
"Oak Grove, Clackamas, Oregon, USA",
"",
"Olmstead, Minnesota, USA",
"",
"Winnebago, Illinois, USA",
"Stevensen, Skamania, Washington, USA",
"Onawa, Monona, Iowa, USA",
"",
"Beemer, Cuming, Nebraska, USA",
"Nodaway, Missouri, USA",
"Delaware, Ohio, USA",
"Chester, Pennsylvania, USA",
"",
"",
""
]
Dwr.ScriptLoaded('dwr_db_F_marr_place_0.js');
