// This file is generated

C_text_0 = [
"",
"<p>\n<b>\nDate: \n</b>\n10/12/2020\n</p>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nDate: \n</b>\n3/7/1955\n</p>",
"",
"<p>\n<b>\nDate: \n</b>\n1920\n</p>",
"",
"<p>\n<b>\nDate: \n</b>\n1910\n</p>",
"<p>\n<b>\nDate: \n</b>\n1860\n</p>",
"",
"<p>\n<b>\nDate: \n</b>\n1820\n</p>",
"<p>\n<b>\nDate: \n</b>\n1830\n</p>",
"",
"<p>\n<b>\nDate: \n</b>\n1830\n</p>",
"<p>\n<b>\nDate: \n</b>\n1860\n</p>",
"",
"<p>\n<b>\nDate: \n</b>\n2009\n</p>",
"",
"",
"<p>\n<b>\nPage: \n</b>\n\"Illinois, County Marriages, 1810-1940\", , FamilySearch (https://www.familysearch.org/ark:/61903/1:1:QK9L-5PRV : Wed Jan 22 00:41:31 UTC 2025), Entry for Augustus R Swetland and Charlotte A Adams, 04 Nov 1846.\n</p>",
"<p>\n<b>\nDate: \n</b>\n1910\n</p><p>\n<b>\nPage: \n</b>\n\"Indiana, United States records,\" images, FamilySearch (https://www.familysearch.org/ark:/61903/3:1:33SQ-GRV9-FX7?view=index : Feb 19, 2025), image 979 of 1442; United States. National Archives and Records Administration.\n</p>",
"<p>\n<b>\nPage: \n</b>\n\"Ringgold, Iowa, United States records,\" images, FamilySearch (https://www.familysearch.org/ark:/61903/3:1:3QHJ-5QHW-TTPC?view=index : Feb 19, 2025), image 5 of 18; National Archives and Records Administration.\n</p>",
"<p>\n<b>\nPage: \n</b>\n109 - 113\n</p>",
"<p>\n<b>\nDate: \n</b>\n11/27/1971\n</p><p>\n<b>\nPage: \n</b>\n168\n</p>",
"<p>\n<b>\nDate: \n</b>\n7/9/1972\n</p><p>\n<b>\nPage: \n</b>\n168\n</p>",
"<p>\n<b>\nDate: \n</b>\n4/1/1971\n</p><p>\n<b>\nPage: \n</b>\n171\n</p>",
"<p>\n<b>\nPage: \n</b>\n1887-2001 John Squier/Daniel Squier; https://www.familysearch.org/ark:/61903/1:1:WLGL-YJPZ\n</p>",
"<p>\n<b>\nPage: \n</b>\n1920-1940\n</p>",
"<p>\n<b>\nDate: \n</b>\n1940\n</p><p>\n<b>\nPage: \n</b>\n1940; Census Place: Stevens, Spokane, Washington; Roll: m-t0627-04363; Page: 1A; Enumeration District: 32-64\n</p>",
"<p>\n<b>\nDate: \n</b>\nbetween 1906 and 2009\n</p><p>\n<b>\nPage: \n</b>\n1946 - 1955; Page 139 of 154\n</p>",
"<p>\n<b>\nDate: \n</b>\n1975\n</p><p>\n<b>\nPage: \n</b>\n198 - 201\n</p>",
"<p>\n<b>\nPage: \n</b>\n276\n</p>",
"<p>\n<b>\nPage: \n</b>\n284\n</p>",
"<p>\n<b>\nPage: \n</b>\n48 - 52\n</p>",
"<p>\n<b>\nPage: \n</b>\nAncestry.com. Indiana, U.S., Marriage Certificates, 1960-2012 [database on-line]. Lehi, UT, USA: Ancestry.com Operations, Inc., 2016.\n</p>",
"<p>\n<b>\nDate: \n</b>\n1915\n</p><p>\n<b>\nPage: \n</b>\nBenton\n</p>",
"<p>\n<b>\nDate: \n</b>\nbetween 1940 and 1997\n</p><p>\n<b>\nPage: \n</b>\nBernice Loretta Goforth (Dukes); https://familysearch.org/ark:/61903/1:1:VPMK-NVL\n</p>",
"<p>\n<b>\nPage: \n</b>\nBernice Loretta Goforth; https://records.myheritagelibraryedition.com/research/record-1-339007801-1-528875/bernice-loretta-beals-born-goforth-in-myheritage-family-trees\n</p>",
"<p>\n<b>\nDate: \n</b>\nbetween 1880 and 1946\n</p><p>\n<b>\nPage: \n</b>\nBirth Records > Ringgold County > 1923-1943 : Page 1945 of 3335\n</p>",
"<p>\n<b>\nDate: \n</b>\n1870\n</p><p>\n<b>\nPage: \n</b>\nBurnside, Clearfield, Pennsylvania\n</p>",
"<p>\n<b>\nDate: \n</b>\n1900\n</p><p>\n<b>\nPage: \n</b>\nCenter, Greene, Indiana\n</p>",
"<p>\n<b>\nDate: \n</b>\n1860\n</p><p>\n<b>\nPage: \n</b>\nChest, Cambria, Pennsylvania\n</p>",
"<p>\n<b>\nDate: \n</b>\n1850\n</p><p>\n<b>\nPage: \n</b>\nChest, Clearfield, Pennsylvania\n</p>",
"<p>\n<b>\nPage: \n</b>\nClaire Miller\n</p>",
"<p>\n<b>\nPage: \n</b>\nClark County, Indiana;marriage Records 1897 - 1901\n</p>",
"<p>\n<b>\nPage: \n</b>\nconniejayne\n</p>",
"<p>\n<b>\nDate: \n</b>\n1930\n</p><p>\n<b>\nPage: \n</b>\nCunningham, Coos\n</p>",
"<p>\n<b>\nPage: \n</b>\nDaniel Squire II; https://www.findagrave.com/memorial/77298859/daniel-squire\n</p>",
"<p>\n<b>\nPage: \n</b>\ndeanpratt41\n</p>",
"<p>\n<b>\nPage: \n</b>\ndennissquier\n</p>",
"<p>\n<b>\nDate: \n</b>\n1850\n</p><p>\n<b>\nPage: \n</b>\nDistrict 22, Taylor, Iowa\n</p>",
"<p>\n<b>\nDate: \n</b>\n1950\n</p><p>\n<b>\nPage: \n</b>\nDouglas > Beechwood\n</p>",
"<p>\n<b>\nPage: \n</b>\nEdward Hudson Cowell - https://www.findagrave.com/memorial/62536962/edward-hudson-cowell\n</p>",
"<p>\n<b>\nPage: \n</b>\nEdward Hudson Cowell; https://www.findagrave.com/memorial/62536962/edward-hudson-cowell\n</p>",
"<p>\n<b>\nDate: \n</b>\n1880\n</p><p>\n<b>\nPage: \n</b>\nElder, Cambria, Pennsylvania\n</p>",
"<p>\n<b>\nPage: \n</b>\nElias Stone Cowell; https://www.findagrave.com/memorial/16886656/elias-stone-cowell\n</p>",
"<p>\n<b>\nPage: \n</b>\nElijah Roger Holm - https://www.findagrave.com/memorial/128587380/elijah-roger-holm\n</p>",
"<p>\n<b>\nPage: \n</b>\nEmerson P Squier\n</p>",
"<p>\n<b>\nPage: \n</b>\nEmerson Porter Squier; https://www.familysearch.org/ark:/61903/1:1:QP45-KVJN\n</p>",
"<p>\n<b>\nPage: \n</b>\nEmerson Porter Squier; https://www.findagrave.com/memorial/118896873/emerson-porter-squier\n</p>",
"<p>\n<b>\nPage: \n</b>\nEpiscopal Diocese of Spokane; Spokane, Washington; The Episcopal Diocese of Spokane Church Records\n</p>",
"<p>\n<b>\nPage: \n</b>\nEvangelical Lutheran Church in America Archives; Elk Grove Village, Illinois; Congregational Records\n</p>",
"<p>\n<b>\nPage: \n</b>\nFlora Bell Horton; https://www.findagrave.com/memorial/250171738/flora_bell-squier\n</p>",
"<p>\n<b>\nPage: \n</b>\nFloyd Miles Squier; https://www.findagrave.com/memorial/30988295/floyd-miles-squier\n</p>",
"<p>\n<b>\nPage: \n</b>\nFRANKIE_HUGHES27\n</p>",
"<p>\n<b>\nDate: \n</b>\n1930\n</p><p>\n<b>\nPage: \n</b>\nFremont, Dodge, Nebraska\n</p>",
"<p>\n<b>\nDate: \n</b>\n1850\n</p><p>\n<b>\nPage: \n</b>\nFulton and Greene Counties, Pennsylvania\n</p>",
"<p>\n<b>\nPage: \n</b>\nGordon Lee Swetland; https://www.findagrave.com/memorial/240540663/gordon-lee-swetland\n</p>",
"<p>\n<b>\nDate: \n</b>\n1942\n</p><p>\n<b>\nPage: \n</b>\nGroup Number: 147 Name Range: Baadsgaard, Anker - Gwinup, Harry Frank\n</p>",
"<p>\n<b>\nDate: \n</b>\n1850\n</p><p>\n<b>\nPage: \n</b>\nGuilford, Winnebago, Illinois, USA\n</p>",
"<p>\n<b>\nPage: \n</b>\nhe National Archives At St. Louis; St. Louis, Missouri; World War Ii Draft Cards (Fourth Registration) For the State of Nebraska; Record Group Title: Records of the Selective Service System; Record Group Number: 147; Box or Roll Number: 1288 Name Range: Sullivan, Henry Lawrence - Swift, Seth Serat -\n</p>",
"<p>\n<b>\nPage: \n</b>\nHenry John Beal - https://www.findagrave.com/memorial/61125730/henry-j.-beal\n</p>",
"<p>\n<b>\nDate: \n</b>\n10/24/1913\n</p><p>\n<b>\nPage: \n</b>\nHenry John Beals; https://www.familysearch.org/tree/person/sources/LJVY-KH7\n</p>",
"<p>\n<b>\nPage: \n</b>\nHillW2\n</p>",
"<p>\n<b>\nPage: \n</b>\nHistorical Data Systems, comp. U.S., Civil War Soldier Records and Profiles, 1861-1865\n</p>",
"<p>\n<b>\nPage: \n</b>\nhttps://iowagravestones.org/gs_view.php?id=509873\n</p>",
"<p>\n<b>\nPage: \n</b>\nhttps://www.findagrave.com/memorial/11865100/hiram-tharp\n</p>",
"<p>\n<b>\nPage: \n</b>\nhttps://www.findagrave.com/memorial/16886666/jair-willard-cowell?_gl=1*1w4psxc*_gcl_au*Mjc4NDU3MjM3LjE3NDkwOTgwNDk.*_ga*ODcxMDI4NjQ5LjE3MzEyMTM0MzI.*_ga_4QT8FMEX30*czVjOGRjZmVmLWI2ZTMtNGRhMy1hMmY2LTM1ODY5ZDlmYmRiOCRvNTkkZzEkdDE3NDk5MzgxMzckajMyJGwwJGgw*_ga_LMK6K2LSJH*czVjOGRjZmVmLWI2ZTMtNGRhMy1hMmY2LTM1ODY5ZDlmYmRiOCRvNTkkZzEkdDE3NDk5MzgxMzckajMzJGwwJGgw\n</p>",
"<p>\n<b>\nPage: \n</b>\nhttps://www.findagrave.com/memorial/89155835/joseph-barton\n</p>",
"<p>\n<b>\nDate: \n</b>\nbetween 1917 and 1918\n</p><p>\n<b>\nPage: \n</b>\nhttps://www.fold3.com/publication/959/us-wwi-draft-registration-cards-1917-1918\n</p>",
"<p>\n<b>\nPage: \n</b>\nIndiana, U.S., Marriage Certificates, 1960-2012 [database on-line]. Lehi, UT, USA: Ancestry.com Operations, Inc., 2016.\n</p>",
"<p>\n<b>\nPage: \n</b>\nIowa Birth Records, 1888-1904\n</p>",
"<p>\n<b>\nPage: \n</b>\nIowa Births and Christenings, 1830\u20131950.\" Index. FamilySearch, Salt Lake City, Utah, 2009, 2010.\n</p>",
"<p>\n<b>\nPage: \n</b>\nIowa Department of Public Health; Des Moines, Iowa; Iowa Marriage Records, 1880\u20131922; Record Type: Marriage Volume: 314 (Harrison - Kossuth)\n</p>",
"<p>\n<b>\nPage: \n</b>\nIowa Department of Public Health; Des Moines, Iowa; Iowa Marriage Records, 1923\u20131937; Record Type: Marriage Volume: 3\n</p>",
"<p>\n<b>\nPage: \n</b>\nIowa, U.S., Death Records, 1880-1968; 1921-1929 (Ringgold County)\n</p>",
"<p>\n<b>\nPage: \n</b>\nIowa, U.S., Grand Army of the Republic Membership Records, ca. 1866-ca.1950\n</p>",
"<p>\n<b>\nPage: \n</b>\nIowa, U.S., Marriage Records, 1880-1948; Paul Cowell and Vernice Hudson\n</p>",
"<p>\n<b>\nPage: \n</b>\nIowa, U.S., Select Marriages Index, 1758-1996\n</p>",
"<p>\n<b>\nPage: \n</b>\nIowa, U.S., Select Marriages Index, 1758-1996\n</p>",
"<p>\n<b>\nPage: \n</b>\nIsaac Cowell\n</p>",
"<p>\n<b>\nPage: \n</b>\nIsaac Cowell\n</p>",
"<p>\n<b>\nPage: \n</b>\nIsaac Cowell (and Christian Cowell, possibly unrelated, researching)\n</p>",
"<p>\n<b>\nPage: \n</b>\nIsaac Cowell; Job number 10-001, Nara catalog id2733385, Record group 217\n</p>",
"<p>\n<b>\nDate: \n</b>\n1860\n</p><p>\n<b>\nPage: \n</b>\nJackson, Taylor, Iowa\n</p>",
"<p>\n<b>\nDate: \n</b>\n1860\n</p><p>\n<b>\nPage: \n</b>\nJefferson, Pope, Illinois\n</p>",
"<p>\n<b>\nPage: \n</b>\nJeremy Holm\n</p>",
"<p>\n<b>\nPage: \n</b>\nJHolm73\n</p>",
"<p>\n<b>\nPage: \n</b>\nJoan Loretta Stanphill born Beal; https://records.myheritagelibraryedition.com/research/record-1-339007801-1-528900/joan-loretta-stanphill-born-beal-in-myheritage-family-trees\n</p>",
"<p>\n<b>\nPage: \n</b>\nJohn Henry Beals; https://records.myheritagelibraryedition.com/research/record-1-339007801-1-528857/john-henry-beals-in-myheritage-family-trees\n</p>",
"<p>\n<b>\nDate: \n</b>\n1/15/1909\n</p><p>\n<b>\nPage: \n</b>\nJohn L Squier Obituary\n</p>",
"<p>\n<b>\nPage: \n</b>\nJohn L Squier; https://www.findagrave.com/memorial/132426767/john-lytle-squier ; Includes excerpt from book \"History of Rice County 1882\"\n</p>",
"<p>\n<b>\nPage: \n</b>\nJohn S Beal; https://www.findagrave.com/memorial/63046540/john-s-beal\n</p>",
"<p>\n<b>\nPage: \n</b>\nJohn Stepherson Beals; https://records.myheritagelibraryedition.com/research/record-1-339007801-1-528856/john-stepherson-beals-in-myheritage-family-trees\n</p>",
"<p>\n<b>\nDate: \n</b>\n1940\n</p><p>\n<b>\nPage: \n</b>\nJohn Steven Beal\n</p>",
"<p>\n<b>\nDate: \n</b>\n1930\n</p><p>\n<b>\nPage: \n</b>\nKennewick\n</p>",
"<p>\n<b>\nPage: \n</b>\nLibrary and Archives Canada; Ottawa, ON, Canada; Passenger Lists, 1865-1935; Series: RG 76-C; Roll: C-4538 Month: 11\n</p>",
"<p>\n<b>\nPage: \n</b>\nManasseh Wildman\n</p>",
"<p>\n<b>\nPage: \n</b>\nMap of Grant Township\n</p>",
"<p>\n<b>\nPage: \n</b>\nmarillionflower\n</p>",
"<p>\n<b>\nPage: \n</b>\nMarion Johnson\n</p>",
"<p>\n<b>\nPage: \n</b>\nMarriage Certificates 1957 Jan-Apr\n</p>",
"<p>\n<b>\nPage: \n</b>\nmartacitaw\n</p>",
"<p>\n<b>\nPage: \n</b>\nmelanieaustin1\n</p>",
"<p>\n<b>\nPage: \n</b>\nmoms.mn.gov; Minnesota, U.S., Marriages from the Minnesota Official Marriage System, 1850-2022\n</p>",
"<p>\n<b>\nDate: \n</b>\n11/25/1940\n</p><p>\n<b>\nPage: \n</b>\nNancy Maria Squier\n</p>",
"<p>\n<b>\nPage: \n</b>\nNational Archives at St. Louis; St. Louis, Missouri; Wwii Draft Registration Cards For Nebraska, 10/16/1940-03/31/1947; Record Group: Records of the Selective Service System, 147; Box: 105 Name Range: Sward, Carl-Tenopin, Robert\n</p>",
"<p>\n<b>\nPage: \n</b>\nndiana Archives and Records Administration; Indianapolis, IN, USA; Indiana, U.S., Death Certificates, 1899-2011; Year: 1922; Roll: 02\n</p>",
"<p>\n<b>\nPage: \n</b>\nNebraska Death Index, 1956-1968\n</p>",
"<p>\n<b>\nPage: \n</b>\nNebraska Department of Health and Human Services; Lincoln, Nebraska; Nebraska Birth Index, 1912-1994\n</p>",
"<p>\n<b>\nPage: \n</b>\nNebraska Department of Health and Human Services; Lincoln, Nebraska; Nebraska Death Index, 1956-1968\n</p>",
"<p>\n<b>\nPage: \n</b>\nNellie Mae Barton; https://records.myheritagelibraryedition.com/research/record-1-339007801-1-528867/nellie-mae-barton-in-myheritage-family-trees\n</p>",
"<p>\n<b>\nPage: \n</b>\nNew England Historic Genealogical Society; Boston, Massachusetts; State of Vermont. Vermont Vital Records through 1870DescriptionSurname Range: Squires, D-Starks, M\n</p>",
"<p>\n<b>\nDate: \n</b>\n1855\n</p><p>\n<b>\nPage: \n</b>\nNew York State Archives; Albany, NY, USA; Census of the state of New York, 1855\n</p>",
"<p>\n<b>\nDate: \n</b>\n1850\n</p><p>\n<b>\nPage: \n</b>\nNoble, Indiana, United States records,\" images, FamilySearch (https://www.familysearch.org/ark:/61903/3:1:S3HT-67JS-QNN?view=explore : Jul 24, 2025), image 197 of 585; United States. National Archives and Records Administration. Image Group Number: 004192467\n</p>",
"<p>\n<b>\nDate: \n</b>\n1971\n</p><p>\n<b>\nPage: \n</b>\nOregon Center for Health Statistics; Portland, Oregon, USA; Oregon, Death Records, 1969-1971\n</p>",
"<p>\n<b>\nPage: \n</b>\nOregon Divorce Records, 1961-1985. Oregon Center for Health Statistics, Portland, Oregon.\n</p>",
"<p>\n<b>\nPage: \n</b>\nOregon State Archives; Salem, Oregon; Oregon, Death Records, 1864-1967\n</p>",
"<p>\n<b>\nPage: \n</b>\nOregon State Library; 1966-1970 Death Index; Reel Title: State of Oregon Death Index; Year Range: 1971-1980\n</p>",
"<p>\n<b>\nPage: \n</b>\nOregon State Library; 1966-1970 Death Index; Reel Title: State of Oregon Death Index; Year Range: 1981-1990\n</p>",
"<p>\n<b>\nPage: \n</b>\nOregon State Library; 1966-1970 Death Index; Reel Title: State of Oregon Death Index; Year Range: 1981-1990\n</p>",
"<p>\n<b>\nPage: \n</b>\nOregon State Library; Oregon Death Index 1931-1941; Reel Title: Oregon Death Index M-Z; Year Range: 1931-1941; First Letter of Surname: H\n</p>",
"<p>\n<b>\nPage: \n</b>\nOregon State Library; Oregon Death Index 1931-1941; Reel Title: State of Oregon Death Index; Year Range: 1991-2000\n</p>",
"<p>\n<b>\nPage: \n</b>\nOregon State Library; Oregon Death Indexes, 1971-2008; Reel Title: State of Oregon Death Index; Year Range: 2001-2005 First Letter of Surname: S\n</p>",
"<p>\n<b>\nPage: \n</b>\nOregon, U.S., Death Index 1898-2008; Vernice Hudson Page 1483\n</p>",
"<p>\n<b>\nDate: \n</b>\n7/9/1957\n</p><p>\n<b>\nPage: \n</b>\nPage 1\n</p>",
"<p>\n<b>\nDate: \n</b>\n9/3/1884\n</p><p>\n<b>\nPage: \n</b>\nPage 1\n</p>",
"<p>\n<b>\nDate: \n</b>\n1/11/1912\n</p><p>\n<b>\nPage: \n</b>\nPage 1\n</p>",
"<p>\n<b>\nDate: \n</b>\n3/7/1899\n</p><p>\n<b>\nPage: \n</b>\nPage 1\n</p>",
"<p>\n<b>\nDate: \n</b>\n3/30/1916\n</p><p>\n<b>\nPage: \n</b>\nPage 1\n</p>",
"<p>\n<b>\nDate: \n</b>\n10/31/1957\n</p><p>\n<b>\nPage: \n</b>\nPage 1\n</p>",
"<p>\n<b>\nDate: \n</b>\n2/11/1927\n</p><p>\n<b>\nPage: \n</b>\nPage 1\n</p>",
"<p>\n<b>\nDate: \n</b>\n5/18/1882\n</p><p>\n<b>\nPage: \n</b>\nPage 1\n</p>",
"<p>\n<b>\nDate: \n</b>\n2/24/1944\n</p><p>\n<b>\nPage: \n</b>\nPage 10\n</p>",
"<p>\n<b>\nDate: \n</b>\n10/30/1954\n</p><p>\n<b>\nPage: \n</b>\nPage 18\n</p>",
"<p>\n<b>\nDate: \n</b>\n7/11/1957\n</p><p>\n<b>\nPage: \n</b>\nPage 2\n</p>",
"<p>\n<b>\nDate: \n</b>\n4/4/1902\n</p><p>\n<b>\nPage: \n</b>\nPage 2\n</p>",
"<p>\n<b>\nDate: \n</b>\n11/3/1865\n</p><p>\n<b>\nPage: \n</b>\nPage 2\n</p>",
"<p>\n<b>\nDate: \n</b>\n1/15/1897\n</p><p>\n<b>\nPage: \n</b>\nPage 2\n</p>",
"<p>\n<b>\nDate: \n</b>\n3/25/1958\n</p><p>\n<b>\nPage: \n</b>\nPage 2\n</p>",
"<p>\n<b>\nDate: \n</b>\n10/23/186\n</p><p>\n<b>\nPage: \n</b>\nPage 3\n</p>",
"<p>\n<b>\nDate: \n</b>\n11/21/1889\n</p><p>\n<b>\nPage: \n</b>\nPage 3\n</p>",
"<p>\n<b>\nDate: \n</b>\n5/10/1895\n</p><p>\n<b>\nPage: \n</b>\nPage 3\n</p>",
"<p>\n<b>\nDate: \n</b>\n8/1/1934\n</p><p>\n<b>\nPage: \n</b>\nPage 3\n</p>",
"<p>\n<b>\nDate: \n</b>\n12/28/1945\n</p><p>\n<b>\nPage: \n</b>\nPage 3\n</p>",
"<p>\n<b>\nPage: \n</b>\nPage 311; Jacob Cowell Will; https://familysearch.org/pal:/MM9.3.1/TH-1971-28809-13772-3?cc=1999196&wc=M99F-4DC:1339609058\n</p>",
"<p>\n<b>\nDate: \n</b>\n1/6/1966\n</p><p>\n<b>\nPage: \n</b>\nPage 39\n</p>",
"<p>\n<b>\nDate: \n</b>\n11/19/1915\n</p><p>\n<b>\nPage: \n</b>\nPage 4\n</p>",
"<p>\n<b>\nDate: \n</b>\n4/10/1941\n</p><p>\n<b>\nPage: \n</b>\nPage 5\n</p>",
"<p>\n<b>\nDate: \n</b>\n4/3/1958\n</p><p>\n<b>\nPage: \n</b>\nPage 5\n</p>",
"<p>\n<b>\nDate: \n</b>\n11/26/1940\n</p><p>\n<b>\nPage: \n</b>\nPage 5\n</p>",
"<p>\n<b>\nDate: \n</b>\n2/1/1927\n</p><p>\n<b>\nPage: \n</b>\nPage 5\n</p>",
"<p>\n<b>\nDate: \n</b>\n2/23/1953\n</p><p>\n<b>\nPage: \n</b>\nPage 7\n</p>",
"<p>\n<b>\nDate: \n</b>\n8/14/1954\n</p><p>\n<b>\nPage: \n</b>\nPage 7\n</p>",
"<p>\n<b>\nDate: \n</b>\n10/19/1957\n</p><p>\n<b>\nPage: \n</b>\nPage 7\n</p>",
"<p>\n<b>\nDate: \n</b>\n5/30/1966\n</p><p>\n<b>\nPage: \n</b>\nPage 7\n</p>",
"<p>\n<b>\nDate: \n</b>\n12/20/1973\n</p><p>\n<b>\nPage: \n</b>\nPage 8\n</p>",
"<p>\n<b>\nDate: \n</b>\n8/9/1917\n</p><p>\n<b>\nPage: \n</b>\nPage Z1\n</p>",
"<p>\n<b>\nDate: \n</b>\n9/10/1942\n</p><p>\n<b>\nPage: \n</b>\nPage Z1\n</p>",
"<p>\n<b>\nPage: \n</b>\nPaul Revere Cowell; https://www.findagrave.com/memorial/30985882/paul-revere-cowell\n</p>",
"<p>\n<b>\nPage: \n</b>\nPhoto added by JEW\n</p>",
"<p>\n<b>\nPage: \n</b>\nPhoto of Mary Ashcraft shared by ChristineAlderman1\n</p>",
"<p>\n<b>\nDate: \n</b>\n1850\n</p><p>\n<b>\nPage: \n</b>\nPike Township\n</p>",
"<p>\n<b>\nDate: \n</b>\n1860\n</p><p>\n<b>\nPage: \n</b>\nPike Township\n</p>",
"<p>\n<b>\nPage: \n</b>\nPresbyterian Historical Society; Philadelphia, PA, USA; US, Presbyterian Church Records, 1701-1907; Book Title: Session Minutes and Register 1927-1955; Accession Number: V Mi46 W852fs; Year: 1926-1970\n</p>",
"<p>\n<b>\nPage: \n</b>\nPSWETLAND73\n</p>",
"<p>\n<b>\nPage: \n</b>\nRAkin3165\n</p>",
"<p>\n<b>\nPage: \n</b>\nRebecca Robertson\n</p>",
"<p>\n<b>\nPage: \n</b>\nRecord Group Number: 147; Box or Roll Number: 1266 Name Range: Post, Wesley - Pruzor, Louis\n</p>",
"<p>\n<b>\nDate: \n</b>\n1880\n</p><p>\n<b>\nPage: \n</b>\nRice County (Wells township)\n</p>",
"<p>\n<b>\nDate: \n</b>\n1895\n</p><p>\n<b>\nPage: \n</b>\nRinggold; https://familysearch.org/ark:/61903/3:1:939V-RQGV-1?cc=1803957&wc=M612-Y68%3A145649001\n</p>",
"<p>\n<b>\nDate: \n</b>\n1954\n</p><p>\n<b>\nPage: \n</b>\nRoseburg High School\n</p>",
"<p>\n<b>\nPage: \n</b>\nScheuermann (Yagodnaya Polyana)\n</p>",
"<p>\n<b>\nDate: \n</b>\n1880\n</p><p>\n<b>\nPage: \n</b>\nSigourney, Keokuk, Iowa\n</p>",
"<p>\n<b>\nDate: \n</b>\n1920\n</p><p>\n<b>\nPage: \n</b>\nSmead Township\n</p>",
"<p>\n<b>\nPage: \n</b>\nSmead xx Sanders Profile\n</p>",
"<p>\n<b>\nPage: \n</b>\nSons of the American Revolution Membership Applications, 1889-1970\n</p>",
"<p>\n<b>\nPage: \n</b>\nSophia Cowell (Sedwick) https://www.findagrave.com/memorial/10722495/sophia-cowell\n</p>",
"<p>\n<b>\nDate: \n</b>\n1875\n</p><p>\n<b>\nPage: \n</b>\nSource CitationNew York State Archives; Albany, NY, USA; Census of the State of New York, 1875DescriptionDistrict: E\u00b7D\u00b7 04\n</p>",
"<p>\n<b>\nDate: \n</b>\n1870\n</p><p>\n<b>\nPage: \n</b>\nSource CitationYear: 1870; Census Place: Deerpark, Orange, New York; Roll: M593_1067; Page: 373ADescriptionTownship: Deerpark\n</p>",
"<p>\n<b>\nPage: \n</b>\nSource number: 27.000; Source type: Electronic Database; Number of Pages: 1; Submitter Code: BZ1\n</p>",
"<p>\n<b>\nDate: \n</b>\n1949\n</p><p>\n<b>\nPage: \n</b>\nState Historical Society of Iowa; Des Moines, IA, USA; Iowa Death Records, 1921-1940\n</p>",
"<p>\n<b>\nPage: \n</b>\nState Historical Society of Iowa; Des Moines, IA, USA; Iowa Death Records, 1921-1940DescriptionYear: 1921-1929 (Jefferson County)\n</p>",
"<p>\n<b>\nPage: \n</b>\nState Historical Society of Iowa; Des Moines, IA, USA; Iowa Death Records, 1952-1967; Reference: 18-0688_us-Ia\n</p>",
"<p>\n<b>\nPage: \n</b>\nState Historical Society of Iowa; Des Moines, IA, USA; Iowa Death Records, 1952-1967; Reference: 18-0688_us-Ia Year: 1961\n</p>",
"<p>\n<b>\nPage: \n</b>\nState Library and Archives, Nebraska State Historical Society; Lincoln, Nebraska; Nebraska, Marriage Records Year Range: 1900-1908\n</p>",
"<p>\n<b>\nDate: \n</b>\n1950\n</p><p>\n<b>\nPage: \n</b>\nStevens, Spokane, Washington, USA\n</p>",
"<p>\n<b>\nDate: \n</b>\n5/19/2022\n</p><p>\n<b>\nPage: \n</b>\nswissmiss16\n</p>",
"<p>\n<b>\nDate: \n</b>\n1860\n</p><p>\n<b>\nPage: \n</b>\nThe National Archives in Washington D.C.; Record Group: Records of the Bureau of the Census; Record Group Number: 29; Series Number: M653; Residence Date: 1860; Home in 1860: Cherry Valley, Winnebago, Illinois; Roll: M653_240; Page: 495; Family History Library Film: 803240\n</p>",
"<p>\n<b>\nDate: \n</b>\n1860\n</p><p>\n<b>\nPage: \n</b>\nThe National Archives in Washington D.C.; Record Group: Records of the Bureau of the Census; Record Group Number: 29; Series Number: M653; Residence Date: 1860; Home in 1860: Shohola, Pike, Pennsylvania; Roll: M653_1176; Page: 913; Family History Library Film: 805176\n</p>",
"<p>\n<b>\nPage: \n</b>\nThe National Archives in Washington D.C.; Record Group: Records of the Bureau of the Census; Record Group Number: 29; Series Number: M653; Residence Date: 1860; Home in 1860: Sigourney, Keokuk, Iowa; Roll: M653_329; Page: 1008; Family History Library Film: 803329\n</p>",
"<p>\n<b>\nDate: \n</b>\n1860\n</p><p>\n<b>\nPage: \n</b>\nThe National Archives in Washington D.C.; Record Group: Records of the Bureau of the Census; Record Group Number: 29; Series Number: M653; Residence Date: 1860; Home in 1860: Sun Prairie, Dane, Wisconsin; Roll: M653_1404; Page: 947; Family History Library Film: 805404\n</p>",
"<p>\n<b>\nPage: \n</b>\nThe National Archives in Washington, DC; Record Group: Records of the Bureau of the Census; Record Group Number: 29; Series Number: M432; Residence Date: 1850; Home in 1850: Cottage Grove, Dane, Wisconsin; Roll: 995; Page: 367b\n</p>",
"<p>\n<b>\nPage: \n</b>\nThe National Archives in Washington, DC; Washington, DC, USA; U.s., Civil War Pension Index: General Index to Pension Files, 1861-1934; NAI Title: General Index to Civil War and Later Pension Files, Ca. 1949-Ca. 1949; NAI Number: 563268; Record Group Title: Records of the Department of Veterans Affairs, 1773-2007; Record Group Number: 15; Series Number: T288; Roll: 197\n</p>",
"<p>\n<b>\nPage: \n</b>\nThe National Archives in Washington, DC; Washington, DC; Soundex Index to Naturalization Petitions For the United States District and Circuit Courts, Northern District of Illinois and Immigration and Naturalization Service District 9, 1840-1950 (M1285); Microfilm Serial: M1285; Microfilm Roll: 79; Roll Description: H-423 P\u00b7 Gust Through H-453 Elizabeth\n</p>",
"<p>\n<b>\nPage: \n</b>\nThomas Fales\n</p>",
"<p>\n<b>\nPage: \n</b>\nThomas Joel Buck\n</p>",
"<p>\n<b>\nDate: \n</b>\n1870\n</p><p>\n<b>\nPage: \n</b>\nTownship 14 Range 6, Pope, Illinois\n</p>",
"<p>\n<b>\nPage: \n</b>\nU.S., Social Security Applications and Claims Index, 1936-2007\n</p>",
"<p>\n<b>\nPage: \n</b>\nU.S., World War I Draft Registration Cards, 1917-1918 Draft Card: S\n</p>",
"<p>\n<b>\nPage: \n</b>\nUnited States, Social Security Numerical Identification Files (NUMIDENT), 1936-2007; https://familysearch.org/ark:/61903/1:1:6KWB-8L48\n</p>",
"<p>\n<b>\nDate: \n</b>\n1885\n</p><p>\n<b>\nPage: \n</b>\nVan Buren, Keokuk, Iowa, USA\n</p>",
"<p>\n<b>\nPage: \n</b>\nVarious Illinois County Courthouses; Various Illinois County Courthouses; Marriage Records; Collection Title: Marriage Records\n</p>",
"<p>\n<b>\nPage: \n</b>\nVernice Hudson\n</p>",
"<p>\n<b>\nDate: \n</b>\n10/20/1921\n</p><p>\n<b>\nPage: \n</b>\nVolume XIX, Number 49, Page 5, Column 4\n</p>",
"<p>\n<b>\nPage: \n</b>\nVolume: 354\n</p>",
"<p>\n<b>\nPage: \n</b>\nWashington Death Index, 1940-2017\n</p>",
"<p>\n<b>\nPage: \n</b>\nWashington State Archives; Olympia, Washington; Washington Death Index, 1940-2017DescriptionYear Range: I2284680\n</p>",
"<p>\n<b>\nPage: \n</b>\nWashington State Archives; Olympia, Washington; Washington Marriage Records, 1854-2013; Reference Number: easpmca45451\n</p>",
"<p>\n<b>\nPage: \n</b>\nWashington State Archives; Olympia, Washington; Washington Marriage Records, 1854-2013; Reference Number: eawhmr2783; Year: Marriages 1907 Sep-Dec\n</p>",
"<p>\n<b>\nPage: \n</b>\nWashington, County Marriages, 1855-2008; Entry for John S Beal and Bernice Goforth; https://familysearch.org/ark:/61903/1:1:QPM5-5FGQ\n</p>",
"<p>\n<b>\nPage: \n</b>\nWashington, County Marriages, 1855-2008; Entry for John S Beal and Bernice Goforth; https://familysearch.org/ark:/61903/1:1:QPMT-9LVV\n</p>",
"<p>\n<b>\nPage: \n</b>\nWashington, U.S., Select Death Index, 1907-1960\n</p>",
"<p>\n<b>\nPage: \n</b>\nWells Township > Rice County > Minnesota\n</p>",
"<p>\n<b>\nPage: \n</b>\nYagodnaya Polyana\n</p>",
"<p>\n<b>\nDate: \n</b>\n1870\n</p><p>\n<b>\nPage: \n</b>\nYear: 1870; Census Place: Auburn, Fayette, Iowa; Roll: M593_391; Page: 4A\n</p>",
"<p>\n<b>\nDate: \n</b>\n1870\n</p><p>\n<b>\nPage: \n</b>\nYear: 1870; Census Place: Lancaster, Keokuk, Iowa; Roll: M593_402; Page: 376A\n</p>",
"<p>\n<b>\nDate: \n</b>\n1880\n</p><p>\n<b>\nPage: \n</b>\nYear: 1880; Census Place: Benton, Ringgold, Iowa; Roll: 362; Page: 43b; Enumeration District: 197\n</p>",
"<p>\n<b>\nDate: \n</b>\n1880\n</p><p>\n<b>\nPage: \n</b>\nYear: 1880; Census Place: Fremont, Fayette, Iowa; Roll: 339; Page: 107a; Enumeration District: 200\n</p>",
"<p>\n<b>\nDate: \n</b>\n1880\n</p><p>\n<b>\nPage: \n</b>\nYear: 1880; Census Place: Sigourney, Keokuk, Iowa; Roll: 349; Page: 158c; Enumeration District: 157\n</p>",
"<p>\n<b>\nPage: \n</b>\nYear: 1900; Census Place: Logan, Cuming, Nebraska; Roll: 920; Page: 12; Enumeration District: 0062\n</p>",
"<p>\n<b>\nPage: \n</b>\nYear: 1900; Census Place: Troy, Latah, Idaho; Roll: 233; Page: 23; Enumeration District: 0068; Enumeration District: 0068; Description: Cornwall Precinct and Troy Precinct Including Troy Town\n</p>",
"<p>\n<b>\nDate: \n</b>\n1900\n</p><p>\n<b>\nPage: \n</b>\nYear: 1900; Census Place: Verdigris, Antelope, Nebraska; Roll: 916; Page: 4; Enumeration District: 0013\n</p>",
"<p>\n<b>\nPage: \n</b>\nYear: 1910; Census Place: Verdigris, Antelope, Nebraska; Roll: T624_838; Page: 7b; Enumeration District: 0013; FHL microfilm: 1374851\n</p>",
"<p>\n<b>\nPage: \n</b>\nYear: 1910; Census Place: Yount, Napa, California; Roll: T624_90; Page: 11a; Enumeration District: 0085; FHL microfilm: 1374103; Enumeration District: 0085; Description: Yount Township (part), excluding Veterans Home of California, Rutherford Precinct, Yount Precinct\n</p>",
"<p>\n<b>\nPage: \n</b>\nYear: 1920; Census Place: Civil District 2, Grundy, Tennessee; Roll: T625_1741; Page: 10A; Enumeration District: 38\n</p>",
"<p>\n<b>\nDate: \n</b>\n1920\n</p><p>\n<b>\nPage: \n</b>\nYear: 1920; Census Place: Pipestone, Pipestone, Minnesota; Roll: T625_850; Page: 10A; Enumeration District: 178\n</p>",
"<p>\n<b>\nPage: \n</b>\nZelaSmith\n</p>"
]
Dwr.ScriptLoaded('dwr_db_C_text_0.js');
