// This file is generated

S_text_0 = [
"<p>\n<b>\nAuthor: \n</b>\nOnline Users\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nUnknown family member\n</p><p>\n<b>\nPublication information: \n</b>\nhttps://www.deschutesmemorial.com/obituaries/Arlene-H-Blackwell?obId=18459556\n</p>",
"",
"",
"<p>\n<b>\nPublication information: \n</b>\nhttps://familysearch.org/ark:/61903/1:1:VPMK-NVL\n</p>",
"",
"",
"",
"",
"",
"<p>\n<b>\nAuthor: \n</b>\nTranscribed by Dixie (Bonnie) - Grand Daughter\n</p><p>\n<b>\nPublication information: \n</b>\nvia Jeremy Holm on Ancestry.com\n</p>",
"",
"<p>\n<b>\nAuthor: \n</b>\nOnline Users\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nRichard D Scheuerman\n</p>",
"",
"<p>\n<b>\nAuthor: \n</b>\nGorden Lee Swetland, Jr\n</p>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nPublication information: \n</b>\nancestry.com\n</p>",
"",
"",
"",
"",
"<p>\n<b>\nPublication information: \n</b>\nhttps://historicmapworks.com/Map/US/27319/Grant+Township/Ringgold+County+1915+Mount+Ayr/Iowa/\n</p>",
"<p>\n<b>\nPublication information: \n</b>\nhttps://historicmapworks.com/Map/US/479074/Wells+Township/Rice+County+1900/Minnesota/\n</p>",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nAuthor: \n</b>\nOnline Users\n</p><p>\n<b>\nPublication information: \n</b>\nhttps://records.myheritagelibraryedition.com/\n</p>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nPublication information: \n</b>\nRebecca Robertson originally shared this on 7 Dec 2016\n</p>",
"",
"",
"",
"<p>\n<b>\nAuthor: \n</b>\nRachael Rayl\n</p>",
"",
"",
"",
"",
"<p>\n<b>\nPublication information: \n</b>\nhttps://volgagermaninstitute.org/surnames/scheuermann-yagodnaya-polyana\n</p>",
"<p>\n<b>\nPublication information: \n</b>\nhttps://roadsidethoughts.com/mt/smead-xx-sanders-profile.htm\n</p>",
"",
"",
"<p>\n<b>\nAuthor: \n</b>\nRichard D. Scheuerman\n</p><p>\n<b>\nPublication information: \n</b>\nhttps://rdscheuerman.wordpress.com/wp-content/uploads/2009/11/berry-meadow-archive-parts-i-iii.pdf\n</p>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nPublication information: \n</b>\nhttps://www.ancestry.com/search/collections/8802/records/1772954\n</p>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nPublication information: \n</b>\nhttps://volgagermaninstitute.org/colonies/yagodnaya-polyana\n</p>"
]
Dwr.ScriptLoaded('dwr_db_S_text_0.js');
