// This file is generated

I_note_0 = [
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n\"Funeral announcement of John Henry Beal, he often went by Henry John Beal, he took off the s off Beals.\"\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nHe was one of the pioneer settlers of Ringgold and Taylor counties.\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nResearch\n</i>\n<div class=\"grampsstylednote\">\n<p>\nIn need the all access tier of ancestry membership to access more records, from Canada\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nOn Find a Grave page:<br />\nMichael Hittle was born 28 April 1776 in Northampton County Pennsylvania, the fourth son and sixth child of thirteen children born to George Michael (1742-1828) Hittel and Christine Hittel.\n</p>\n<p>\nFollowing the end of the Revolutionary War, Michael moved with his father and mother and siblings to Michaelsburg, Fishing Creek, Bloom TWP, Northumberland (later Columbia) County, Pennsylvania. There he grew to manhood and married his first wife, whose name remains unknown. To this union were born 4 children between 1800 - 1812. Michael's spouse died in Fishing Creek and he remarried Lydia Yeaple (1789-1860) between about 1811/12 -1816.\n</p>\n<p>\nIn 1819/1820, Michael and Lydia relocated to Greene County Ohio, where Michael's elder brother George Hittle had settled prior to the War of 1812 and where George was a prominent citizen and one of the county's first Commissioners. Beginning in 1820 with the birth of their son Jacob (1820-1905), born in Greene County Ohio Michael and Lydia Hittle had six children.\n</p>\n<p>\nBetween 1822-1824, Michael and Lydia and their large family pressed westward, relocating from Ohio to Rush County Indiana, where all of their children grew to adulthood.\n</p>\n<p>\nIn 1846, Michael and Lydia followed some of their adult children to Monroe County Iowa, being among the very first settlers to arrive at a place on the prairie then-known as Bremen,and consisting only of a single log building that served as a trading store and tavern. This settlement was 1 mile east of present-day Lovilia, Iowa. Michael Hittle and his sons had invested in several pieces of ground in Union and Brush Creek Townships, and also in Marion County to the north of Monroe County. Several of the original town lots owned by Michael Hittle and his sons were sold to become part of the incorporated town of Lovilia.\n</p>\n<p>\nMichael Hittle was a Blacksmith by occupation. Blind and in ill health, He died in 31 July 1855. He lays at rest in the Osborn Cemetery which sits on the same rising piece of ground of the original settlement of Bremen-- 1 mile east of present-day Lovilia.\n</p>\n<p>\nThe Offspring of Michael Hittle by his first wife, (name unknown)\n</p>\n<p>\n--George Hittle B.1799/00 Fishing Creek, Bloom TWP, Northumberland County, PA<br />\n                          D. Ca. 1844, Rushville, Rush County, IN<br />\n--Nicholas Hittle B.26 Jun 1804, Fishing Creek, Bloom TWP, Northumberland County, PA<br />\n                            D. 24 Aug 1867, Rushville, Rush County, IN<br />\n--Catherine Hittle B.11 Nov 1806, Fishing Creek, Bloom TWP, Northumberland County, PA<br />\n                              D. 23 Jul 1885, Chehalas, Lewis County, WA (Married George Buchanan)-----Elizabeth Hittle B.1813/14 Fishing Creek, Bloom TWP, Northumberland County, PA<br />\n                             D.   Unknown (married twice.  First- Mr, (FNU) Brownlee; Second-<br />\n                             Mr.Findley\n</p>\n<p>\nBy his second wife, Lydia Yeaple Hittle (1789-1860)\n</p>\n<p>\n--Michael Hittle B. 11 July 1816 Fishing Creek, Bloom TWP, Columbia County, PA<br />\n                        D. 15 May 1878 at Lovilia, Union TWP, Monroe County IA<br />\n-- Henry Hittle    B. 15 Jan 1818 near Dayton, Greene County, OH<br />\n                        D, 14 Aug 1897 at Lovilia, Union TWP, Monroe County IA<br />\n--Jacob Hittle*  B. 06 Jun 1820 near Dayton, Greene County, OH<br />\n                        D, 15 Feb 1905 at Good Hope, near Castana, Kennebec TWP<br />\n                            Monona County, IA<br />\n--Mary Ann Hittle B. 1823, Probably Rushville, Rush County, IN<br />\n                           D. Post-1895 (Married to Samuel Kinton)<br />\n--Isaac Hittle     B. 07 Dec 1824, Rushville, Rush County, IN<br />\n                       D.  1904, Hillsdale, Miami County, KS<br />\n--Hartsell Phillip Hittle * (AKA: \"Harts\"  B. 1827/28, Rushville, Rush County, IN<br />\n                                       D, 14 June, 1894 at Lovilia, Monroe County, IN<br />\n--John H. Hittle* B.30 Jun 1830, Rushville, Rush County, IN<br />\n                         D. 01 Jul 1895, Lovilia, Union County, Monroe County, IA<br />\n--Ambulance Hittle  (\"Abalena\") B. ca. 1831/33 Rushville, Rush County IN<br />\n                                                  D. post-1895. probably at Maple Landing,<br />\n                                                   Monona County, IA (Married to George<br />\n                                                   Sappinfield)<br />\n* CIVIL WAR VETERANS:<br />\n     * Jacob Hittle, Corporal, CO A, 36th Iowa Infantry Regiment 1862-1865<br />\n     * John H. Hittle, Company D, 22nd Iowa Infantry Regiment 1862-1865<br />\n     * Isaac Hittle, Southern Border Brigade, Iowa Home Guard Militia<br />\n     * Hartsell P. Hittle, Southern Border Brigade, Iowa Home Guard Militia\n</p>\n</div>\n</div>",
"<div>\n<i class=\"NoteType\">\nResearch\n</i>\n<div class=\"grampsstylednote\">\n<p>\nMultiple people/websites list father as \"Christian Fredrik Andreasen Risholmen\" and mother as \"Anne Dorthea Widdingsdatter Risholmen\" but I haven't been able to find 1 concrete piece of evidence linking them. There is a church record (Norway, Births and Christenings, 1648-1903) for \"Edvart Christiansen\" at Onsoy, Ostfold, Norway referencing this father and mother and but it lists the birth date as 12 Dec 1843 and christening date as 12 Jan 1844, which was before Edward Holm (previously Christiansen) was born. <br />\nThe image for that record is not available.\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\n<span style=\"font-size:12px;\">Obituary</span><br />\nFrom FindaGrave (https://www.findagrave.com/memorial/66835058/helen-harriet-chaney)\n</p>\n<p>\nMrs. Chaney died May 11, 2001, in Roseburg, OR. She was born September 15, 1914 in Hughson, CA and moved with her parents to Sutherlin, OR in 1923.\n</p>\n<p>\nShe was a member of Eastern Star in Oakland, OR and enjoyed traveling, gardening, music and various hobbies.\n</p>\n<p>\nSurvivors include her husband, Howard Chaney; one daughter, Arlene (Cowell) Blackwell and husband Don of Bend, OR,; one son, Delvin Squier and wife Janabel of Redmond, OR.; grandchildren, Dean Cowell and wife Sandi of Bend, OR, Dennis Cowell of Bend, OR, Jerry Blackwell and wife Chris of Chandler, AZ, Darren Squier and wife Angela of Redmond, OR, Steve Squier and wife Tina of Highlands Ranch, CO, Toby Squier and wife Sabrina of Prineville, OR,;step daughter Pamela Wilds and husband Edward of Umpqua, OR.; step grandchildren Nathan and Erin Wilds of Umpqua, OR. Mrs. Chaney is also survived by 12 great-grandchildren and two brothers, Bud Holm and wife Vera of Sutherlin, OR and Norman Holm and wife Marge of Vancouver, WA.\n</p>\n<p>\nMrs. Chaney was preceded in death by her parents, Elijah and Sarah Holm, one brother, Ivan Holm, and two husbands, Floyd Squier and Richard Kemp.\n</p>\n<p>\nA memorial service will be held at the First Methodist Church, 181 E. Second Street in Sutherlin, OR on Saturday, May 19, 2001 at 3 p.m. Private inurnment will be held in the Valley View Cemetery in Sutherlin at a later date.\n</p>\n<p>\n(Obit published in the Roseburg, OR \"The News-Review\")\n</p>\n<p>\n&nbsp;\n</p>\n<p>\nNotes: 1900 U.S. Census for Cornwall, Troy Prec., Troy town, Latah Co., Idaho:<br />\nEdward Holm Head M 56 Norway<br />\nMary Holm Wife F 54 Norway<br />\nJohnnie Holm Son M 20 Norway<br />\nElijah Holm Son M 17 Minn<br />\nMarcus Holm Son M 14 Wisc<br />\nMary Holm Dau F 12 Idaho\n</p>\n<p>\nMary had 5 children, all living.\n</p>\n<p>\n1910 U.S. Census for Yount Twp, Napa Co., CA:<br />\nElijah Holm Head M 26 Minnesota<br />\nSarah Holm Wife F 19 Washington<br />\nIvan Holm Son M 10 mos Idaho\n</p>\n<p>\nElijah Holm's parents &amp; brother Mark &amp; his wife reside next door to him. Sarah has had 1 child, living. Father Edward is a farmer; sons Mark &amp; Elijah are farm laborers.\n</p>\n<p>\nOn Sept. 12, 1918, the Elijah Holm family resided in Soquel, Santa Cruz Co., CA, farming.\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nAccording to obituary: She was a kind and loving mother, a good wife and neighbor. Obituary was signed off \"...our darling mother\" by her living children Robert, James, Howard, Mary, Ada and Elva.\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nDescription according to WWII draft registration card.: Height 5'6\", eye color blue, hair color brown/bald, weight 137, complexion light brown. Small finger on right hand cut off.\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nThere were 2 Johann Henrich's who were born to Johann Hartmann Scheuermann and Elisabeth German. This Johann Henrich was the older of the two (he was 14 in 1766 whereas his younger brother was 8). There were 2 baptism dates listed, 01/03/1753 or 01/20/1755. I am assuming the older date was for this Johann Henrich.<br />\nSource: Volga German Institute page \"Scheuermann (Yagodnaya Polyana)\"\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nThere were rumors in the 1880s that Indians were going to storm Colfax so farmers went in with guns and the excited abated. Mrs. Schierman was once alone and encountered some Indians who seemed threatening. She saw a man riding in the distance on a white horse and said, \u201cMein Mann, Mein Mann,\u201d like he was her husband, so they rode off. Every spring and summer Indians went north through Endicott to the mountains to hunt. Conrad used to say that sometimes it would take a half-day for them all to pass. A group armed with bows and arrows came into Charley Laird\u201fs place one time and told them to cook a meal, but the family sneaked up to Conrad\u201fs and they got their guns. The Indians left but took plates and things down to the river. Another time Mrs. Aschenbrenner cooked biscuits for them. They sometimes camped down by the Lairds and Weitzes on the northwest side of the river.<br />\n(Source: The Berry Meadow Archives page 169 from Mr. Dave Schierman, oral history, Walla Walla, Washington, July 9, 1972 (with Richard Scheuerman and Evelyn Reich).)\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nObituary states: \"Mrs Cowell was always ready and willing to help in sickness and trouble. She was baptized in the Methodist church when a young woman and remained in that faith until death. Grandma Cowell was bedfast almost 5 years and was a patient sufferer all that time. She will be missed by her family, relatives and friends.\"\n</p>\n</div>\n</div>",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nOn Find a Grave page:<br />\nLydia Yeaple Hittle was born in Pennsylvania and nothing else has yet been learned of her early years. She became the second spouse of Michael Hittle (1776-1855) of Fishing Creek, Bloom TWP, Northumberland County (later changed to Columbia County) Pennsylvania. Michael's first wife (name unknown) died circa 1806 leaving him with four small children. Between 1812-1816, Lydia became Michael's second wife. In 1819/1820 Michael and Lydia relocated to Greene County Ohio where Michael's older brother by two years, George Hittle, had moved before the War of 1812. Here, Michael and Lydia had a seventh child, Jacob Hittle (1820-1905) before moving further west and settling in Rush County Indiana by 1824. Here they remained for the next 25 years, raising their large family. Michael was a Blacksmith and farmer.\n</p>\n<p>\n&nbsp;\n</p>\n<p>\n&nbsp;\n</p>\n<p>\nIn 1846 Michael and Lydia followed some of their grown sons to Monroe County Iowa and they were among the original pioneers to settle at a place known as Bremen, 1 mile east of Lovilia. Michael passed away in 1855. Lydia went to her eternal rest in 1860.\n</p>\n<p>\n&nbsp;\n</p>\n<p>\n&nbsp;\n</p>\n<p>\nThe offspring of Michael and Lydia Yeaple Hittle were:\n</p>\n<p>\n&nbsp;\n</p>\n<p>\n&nbsp;\n</p>\n<p>\n--Michael Hittle B. 11 July 1816 Fishing Creek, Bloom TWP, Columbia County, PA\n</p>\n<p>\nD. 15 May 1878 at Lovilia, Union TWP, Monroe County IA\n</p>\n<p>\n--Henry Hittle B. 15 Jan 1818 near Dayton, Greene County, OH\n</p>\n<p>\nD, 14 Aug 1897 at Lovilia, Union TWP, Monroe County IA\n</p>\n<p>\n--Jacob Hittle* B. 06 Jun 1820 near Dayton, Greene County, OH\n</p>\n<p>\nD, 15 Feb 1905 at Good Hope, near Castana, Kennebec TWP\n</p>\n<p>\nMonona County, IA\n</p>\n<p>\n--Mary Ann Hittle B. 1823, Probably Rushville, Rush County, IN\n</p>\n<p>\nD. Post-1895 (Married to Samuel Kinton)\n</p>\n<p>\n--Isaac Hittle B. 07 Dec 1824, Rushville, Rush County, IN\n</p>\n<p>\nD. 1904, Hillsdale, Miami County, KS\n</p>\n<p>\n--Hartsell Phillip Hittle * (AKA: \"Harts\" B. 1827/28, Rushville, Rush County, IN\n</p>\n<p>\nD, 14 June, 1894 at Lovilia, Monroe County, IA\n</p>\n<p>\n--John H. Hittle* B.30 Jun 1830, Rushville, Rush County, IN\n</p>\n<p>\nD. 01 Jul 1895, Lovilia, Union County, Monroe County, IA\n</p>\n<p>\n--Ambulance Hittle (\"Abalena\") B. ca. 1831/33 Rushville, Rush County IN\n</p>\n<p>\nD. post-1895. probably at Maple Landing,\n</p>\n<p>\nMonona County, IA (Married to George\n</p>\n<p>\nSappinfield)\n</p>\n<p>\n* CIVIL WAR VETERANS:\n</p>\n<p>\n* Jacob Hittle, Corporal, CO A, 36th Iowa Infantry Regiment 1862-1865\n</p>\n<p>\n* John H. Hittle, Company D, 22nd Iowa Infantry Regiment 1862-1865\n</p>\n<p>\n* Isaac Hittle, Southern Border Brigade, Iowa Home Guard Militia\n</p>\n<p>\n* Hartsell P. Hittle, Southern Border Brigade, Iowa Home Guard Militia\n</p>\n</div>\n</div>",
""
]
Dwr.ScriptLoaded('dwr_db_I_note_0.js');
