// This file is generated

I_birth_place_0 = [
"New York, USA",
"Pennsylvania, USA",
"",
"Pennsylvania, USA",
"Sigourney, Keokuk, Iowa, USA",
"Pope, Illinois, USA",
"",
"Pittsburgh, Allegheny, Pennsylvania, USA",
"Spokane, Spokane, Washington, USA",
"Cass Lake, Cass, Minnesota, USA",
"North Carolina, USA",
"Sigourney, Keokuk, Iowa, USA",
"Connecticut, USA",
"Connecticut, USA",
"New York, USA",
"",
"Canada",
"Tennessee, USA",
"Mount Ayr, Ringgold, Iowa, USA",
"Greene, Pennsylvania, USA",
"Hunterdon, New Jersey, USA",
"",
"Taylor, Iowa, USA",
"Ringgold, Iowa, USA",
"",
"Kentucky, USA",
"Iowa, USA",
"",
"Reach, Ontario, Canada",
"",
"New York, USA",
"Greene, Pennsylvania, USA",
"",
"Vona, Kit Carson, Colorado, USA",
"",
"Leona, Doniphan, Kansas, USA",
"Wisconsin, USA",
"New York, USA",
"",
"Germany",
"Nebraska, USA",
"",
"Iowa, USA",
"",
"Northampton, Pennsylvania, USA",
"",
"Ohio, USA",
"Northampton, Pennsylvania, USA",
"Fredrikstad, \u00d8stfold, Norway",
"Rice, Minnesota, USA",
"Hughson, Stanislaus, California, USA",
"",
"",
"Minnesota, USA",
"Rochester, Olmstead, Minnesota, USA",
"Pennsylvania, USA",
"Cincinnati, Greene, Indiana, USA",
"Ohio, USA",
"Maxville, Randolph, Indiana, USA",
"Bloomington, Monroe, Indiana, USA",
"Indiana, USA",
"",
"Ohio, USA",
"",
"",
"",
"",
"",
"",
"Norway",
"Ohio, USA",
"Toronto Township, Ontario, Canada",
"Canada",
"England",
"Friend, Saline, Nebraska, USA",
"Fremont, Dodge, Nebraska, USA",
"",
"",
"",
"",
"",
"",
"",
"",
"Russia",
"Endicott, Whitman, Washington, USA",
"Maine, USA",
"",
"Pennsylvania, USA",
"Oakland, Alameda, California, USA",
"Halifax, Windham, Vermont, USA",
"",
"Kingston, Green Lake, Wisconsin, USA",
"Colville, Stevens, Washington, USA",
"Salem, Washington, New York, USA",
"Rice, Minnesota, USA",
"Wyoming, USA",
"Ontario, Canada",
"Pennsylvania, USA",
"Germany",
"Germany",
"New York, USA",
"Verdigris Township, Antelope, Nebraska, USA",
"Royal, Antelope, Nebraska, USA",
"Rockford, Winnebago, Illinois, USA",
"Royal, Antelope, Nebraska, USA",
"Jay, Indiana, USA",
"Pennsylvania, USA",
"Iowa, USA",
"Maryland, USA",
"Waterford, Washington, Ohio, USA",
"",
"",
"Pennsylvania, USA",
"Davidson, Greene, Pennsylvania, USA",
"Pennsylvania, USA",
"",
"Lower Nazareth, Northampton, Pennsylvania, USA",
"Hastings, Cambria, Pennsylvania, USA"
]
Dwr.ScriptLoaded('dwr_db_I_birth_place_0.js');
